import os

from dotenv import load_dotenv


load_dotenv()


TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
ADMIN_USER_IDS = list(map(int, os.getenv('ADMIN_USER_IDS', '').split(',')))

BAHETH_API_BASE_URL = os.getenv('BAHETH_API_BASE_URL')
MEDIA_ENDPOINT = os.getenv('MEDIA_ENDPOINT')
TRANSCRIPTIONS_SEARCH_ENDPOINT = os.getenv('TRANSCRIPTIONS_SEARCH_ENDPOINT')
HADITHS_SEARCH_ENDPOINT = os.getenv('HADITHS_SEARCH_ENDPOINT')
SHAMELA_SEMANTIC_SEARCH_ENDPOINT = os.getenv('SHAMELA_SEMANTIC_SEARCH_ENDPOINT')
BAHETH_API_TOKEN = os.getenv('BAHETH_API_TOKEN')

TURATH_API_BASE_URL = os.getenv('TURATH_API_BASE_URL')
SHAMELA_CLASSICAL_SEARCH_ENDPOINT = os.getenv('SHAMELA_CLASSICAL_SEARCH_ENDPOINT')
